name: humsafar_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  intl: ^0.18.0
  carousel_slider: ^4.1.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.4
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/bg1.jpg
    - images/bg3.jpg
    - images/img1.jpg
    - images/logo1.png
    - images/logo2.png
    - images/multan.jpg
    - images/multan1.jpg
    -  images/seren.jpeg
    -  images/serena_shigar.jpeg
    -  images/shangrila.jpeg
    -  images/JJHotel_ISL.jpeg
    -  images/avariKhi.jpeg
    -  images/f7GH.jpeg
    -  images/hotelMehranKhi.jpeg
    -  images/hunzaembassy.jpeg
    -  images/lahorebackpack.jpeg
    -  images/marriot.jpeg
    -  images/movenpick.jpeg
    -  images/nishatLahore.jpeg
    -  images/oldHunzaInn.jpeg
    -  images/PCLahore.jpg
    -  images/ptdcGilgit.jpeg
    -  images/ptdcSkardu.jpeg
    -  images/rockCitySwat.jpeg
    -  images/serenaGilgit.jpeg
    -  images/serenaHunza.jpeg
    -  images/serenaSwat.jpeg
    -  images/threeStarHotelSwat.jpeg
    -  images/bloomstarQuetta.jpeg
    -  images/PCBhurban.jpeg
    -  images/hotelsmartmultan.jpeg
    -  images/ramadaMultan.jpeg
    -  images/PCGwadar.jpeg
    -  images/sheltonPeshawar.jpeg
    -  images/alqaramMurree.jpeg
    -  images/metroHotelQuetta.jpeg
    -  images/askaniGwadar.jpeg
    -  images/PCPeshawar.jpeg
    -  images/serenaQuetta.jpeg
    -  images/greenHotelMurree.jpg
    -  images/fortroadMultan.jpeg
    -  images/acc.jpeg
    -  images/serena_shigar1.jpeg
    -  images/serena_shigar2.jpeg
    -  images/serena_shigar3.jpeg
    -  images/accommodation.jpeg
    -  images/shangrila1.jpeg
    -  images/shangrila2.jpeg
    -  images/shangrila3.jpeg
    -  images/fortroad1.jpeg
    -  images/fortroad2.jpeg
    -  images/fortroad3.jpeg
    -  images/jjhotel1.jpeg
    -  images/jjhotel2.jpeg
    -  images/jjhotel3.jpeg
    -  images/envcont1.jpeg
    -  images/envcont2.jpeg
    -  images/envcont3.jpeg
    -  images/greenview1.jpeg
    -  images/greenview2.jpeg
    -  images/greenview3.jpeg
    -  images/serenaquetta1.jpeg
    -  images/serenaquetta2.jpeg
    -  images/serenaquetta3.jpeg
    -  images/pcpeshawar1.jpeg
    -  images/pcpeshawar2.jpeg
    -  images/pcpeshawar3.jpeg
    -  images/askani1.jpeg
    -  images/askani2.jpeg
    -  images/askani3.jpeg
    -  images/mehran1.jpeg
    -  images/mehran2.jpeg
    -  images/mehran3.jpeg
    -  images/ptdcgilgit1.jpeg
    -  images/ptdcgilgit2.jpeg
    -  images/ptdcgilgit3.jpeg
    -  images/pclahore1.jpeg
    -  images/pclahore2.jpeg
    -  images/pclahore3.jpeg
    -  images/lahorebp1.jpeg
    -  images/lahorebp2.jpeg
    -  images/lahorebp3.jpeg
    -  images/metroquetta1.jpeg
    -  images/metroquetta2.jpeg
    -  images/metroquetta3.jpeg
    -  images/alqamar1.jpeg
    -  images/alqamar2.jpeg
    -  images/alqamar3.jpeg
    -  images/serenagilgit1.jpeg
    -  images/serenagilgit2.jpeg
    -  images/serenagilgit3.jpeg
    -  images/rockcity1.jpeg
    -  images/rockcity2.jpeg
    -  images/rockcity3.jpeg
    -  images/nishat1.jpeg
    -  images/nishat2.jpeg
    -  images/nishat3.jpeg
    -  images/hotelgraceinn.jpg
    -  images/hotelgrace1.jpg
    -  images/hotelgrace2.jpg
    -  images/hotelgrace3.jpg
    -  images/oldhunza1.jpeg
    -  images/oldhunza2.jpeg
    -  images/oldhunza3.jpeg
    -  images/marriot1.jpeg
    -  images/marriot2.jpeg
    -  images/marriot3.jpeg
    -  images/serenaswat1.jpeg
    -  images/serenaswat2.jpeg
    -  images/serenaswat3.jpeg
    -  images/movenpick1.jpeg
    -  images/movenpick2.jpeg
    -  images/movenpick3.jpeg
    -  images/avari1.jpeg
    -  images/avari2.jpeg
    -  images/avari3.jpeg
    -  images/serenahunza1.jpeg
    -  images/serenahunza2.jpeg
    -  images/serenahunza3.jpeg
    -  images/serenaisl1.jpeg
    -  images/serenaisl2.jpeg
    -  images/serenaisl3.jpeg
    -  images/hotelsmart1.jpeg
    -  images/hotelsmart2.jpeg
    -  images/hotelsmart3.jpeg
    -  images/f71.jpeg
    -  images/f72.jpg
    -  images/f73.jpeg
    -  images/pcbhurban1.jpeg
    -  images/pcbhurban2.jpeg
    -  images/pcbhurban3.jpeg
    -  images/bloomstar1.jpeg
    -  images/bloomstar2.jpeg
    -  images/bloomstar3.jpeg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
