// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAOp7AWxxavNmZEipiFBk_SUQY0jogGDE',
    appId: '1:347294222241:web:7c98b4fde9b63e47a3ede0',
    messagingSenderId: '347294222241',
    projectId: 'humsafarapp-9f009',
    authDomain: 'humsafarapp-9f009.firebaseapp.com',
    storageBucket: 'humsafarapp-9f009.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJGldIE-pD56hvM-VjIC0NeteogA7MgA0',
    appId: '1:347294222241:android:6dbf190983cfec4fa3ede0',
    messagingSenderId: '347294222241',
    projectId: 'humsafarapp-9f009',
    storageBucket: 'humsafarapp-9f009.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMIJHBRnawJuZ6w3oV6OpIgfgZVSf74Ko',
    appId: '1:347294222241:ios:26ae9a5341f5b1dca3ede0',
    messagingSenderId: '347294222241',
    projectId: 'humsafarapp-9f009',
    storageBucket: 'humsafarapp-9f009.firebasestorage.app',
    iosBundleId: 'com.example.humsafarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMIJHBRnawJuZ6w3oV6OpIgfgZVSf74Ko',
    appId: '1:347294222241:ios:26ae9a5341f5b1dca3ede0',
    messagingSenderId: '347294222241',
    projectId: 'humsafarapp-9f009',
    storageBucket: 'humsafarapp-9f009.firebasestorage.app',
    iosBundleId: 'com.example.humsafarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAOp7AWxxavNmZEipiFBk_SUQY0jogGDE',
    appId: '1:347294222241:web:34779800b7898c91a3ede0',
    messagingSenderId: '347294222241',
    projectId: 'humsafarapp-9f009',
    authDomain: 'humsafarapp-9f009.firebaseapp.com',
    storageBucket: 'humsafarapp-9f009.firebasestorage.app',
  );
}
